### ISSUE TITLE
message右上角的社交图标hover时要加个放大动画

### ISSUE THREAD

**Issue by bigzhu** [bigzhu/follow_center#46]
参看 http://semantic-ui.com/elements/icon.html 的效果
 
@sinowisaland

**Comment by sinowisaland** [comment]
使用semantic来么?还是用:hover  transition来呢？

**Comment by sinowisaland** [comment]
参看官网的效果是怎么实现的嘛

**Comment by sinowisaland** [comment]
已经完成。
